### ISSUE TITLE
TypeError: Failed to execute 'digest' on 'SubtleCrypto'

### ISSUE THREAD

**Issue by prajwolrg** [johnoliverdriscoll/ecc-acc#10]
On trying to run the test, I get the following TypeError:
`TypeError: Failed to execute 'digest' on 'SubtleCrypto': 2nd argument is not instance of ArrayBuffer, Buffer, TypedArray, or DataView.`

**Comment by johnoliverdriscoll** [comment]
Resolved by 08d49645eeab8b0a0e5ba7879383779a1ca17111
