### ISSUE TITLE
Please, share a link to the paper this library implements

### ISSUE THREAD

**Issue by seniorjoinu** [johnoliverdriscoll/ecc-acc#6]
I'm trying to figure out how to implement my own ec based accumulator in rust. 
Your implementation is one of few and it would be nice if it could be accompanied with a link to theoretical description of the process.

**Comment by iltumio** [comment]
you should find some information here https://medium.com/asecuritysite-when-bob-met-alice/bloom-filters-merkle-trees-and-accumulators-27bc2f7baf5a. But I'm not sure is the exact same implementation

**Comment by johnoliverdriscoll** [comment]
I *think* I based the implementation off the construction described in [An Accumulator Based on Bilinear Maps and Efficient Revocation for Anonymous Credentials](https://eprint.iacr.org/2008/539.pdf) but it has been so long that I worked on this, I can't be sure. Sorry.
