### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sangaman** [johnoliverdriscoll/ecc-acc#9]
I'm thinking of playing around with this repo and possibly using or modifying some of the code. The package.json mentions an `ISC` license but there is no `LICENSE` file or mention of licensing anywhere else.  Is the code in this repo free to use and modify? Does the ISC license apply? Thanks again!

**Comment by johnoliverdriscoll** [comment]
https://github.com/johnoliverdriscoll/ecc-acc/commit/bc22e57fecdde32302de73656d2b0e4a94c5ab90
